export function Welcome() {
  return (
    <main className="flex min-h-screen items-center justify-center px-6">
      <div className="max-w-xl rounded-lg border border-border bg-background p-8 shadow-sm">
        <h1 className="text-3xl font-semibold tracking-tight">
          Welcome to eventsnare
        </h1>
        <p className="mt-2 text-sm text-muted-foreground">
          App: <code className="font-mono">landing</code>
        </p>
        <p className="mt-6 text-base leading-relaxed">
          This is a fresh scaffold generated by Scaffold Studio. Start by adding
          features in the wizard, plugging in your environment variables, and
          editing this page in <code className="font-mono">src/app/routes/Welcome.tsx</code>.
        </p>
      </div>
    </main>
  );
}
